name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.testlearnbasics.fun }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAUQUHZJEYGFZQ5322 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.wCqR7cAfZGan8Faf4WeZwATEHQNdx6BMK7Zed0PT }}
          AWS_REGION: "ap-south-1"
